# Generated by Django 4.2.4 on 2023-08-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publications',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
