# Generated by Django 4.2.4 on 2023-08-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_publications_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publications',
            old_name='user',
            new_name='profile',
        ),
    ]
